coverage:
  precision: 2
  round: down
  range: 50..100
  status:
    project:
      default:
        # Current baseline: 65.89% as of 2025-11-20 (excluding dist/ artifacts)
        # Goal: 90% - enforced via informational threshold for now
        target: 66
        threshold: "2.0"  # Allow 2% decrease while stabilizing
        if_not_found: failure
        informational: false
    patch:
      default:
        # Require new code to have 80% coverage minimum
        # (working toward 90% goal incrementally)
        target: 80
        threshold: "5.0"
        if_not_found: failure
        informational: false
comment:
  layout: "diff, flags, files"
  require_changes: true
  behavior: default
  
# Ignore files that should not count toward coverage
ignore:
  - "packages/*/dist/**"  # Built artifacts (transpiled duplicates of src/)
  - "packages/*/test/**"  # Test files themselves
  - "packages/*/tests/**"  # Test files themselves
  - "**/node_modules/**"
  - "scripts/**"  # Build/utility scripts
  - "**/tmp/**"  # Temporary test files
