coverage:
  precision: 2
  round: down
  range: 90..100
  status:
    project:
      default:
        target: 90
        threshold: "0.5"
        if_not_found: failure
    patch:
      default:
        target: 90
        threshold: "1.0"
        if_not_found: failure
comment:
  layout: "diff"
  require_changes: true
  behavior: default
